name: Format

on:
  pull_request:
    branches: [master]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
      # To avoid git failure with status 128 ref https://github.com/axel-op/googlejavaformat-action/issues/11
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
